version: '3'

services:
  db:
    image: 'mysql:5.7'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    restart: always
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    restart: always
    networks:
      - laravel

  web:
    image: 'shinsenter/laravel:latest'
    depends_on:
      - db
    links:
      - db
    ports:
      - "7000:80"
    volumes:
      - '.:/var/www/html'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=userdb
      - DB_USERNAME=user
      - DB_PASSWORD=password
    restart: always
    networks:
      - laravel

volumes:
  db_data: 
networks:
  laravel:
